# The Golem of Prague

## Using `rethinking`, `brms` and `loo`

All models and computations use the `brms` package @R-brms.
It  is inspired from *Solomon Kurtz* who did wonderful work. It is all detailed
at [Solomon Kurtz](https://bookdown.org/content/3890/).

This is important as, `rethinking` R-rethinking is not used in 
real-life applications whereas `brms` is considered a reference.

The `loo` package @R-loo is used by both `rethinking` and `brms` to compute
WAIC and LOO.  See chapter 7 *Ulysses' compass*, section 7.5, for details.

## Using `tidyverse`

A fundamental role of this study project is, in addition to learning Bayesian
statistics, to learn *how to use a tool kit* which is inseparable from the
study of Bayesian stats.  Therefore the `tidyverse` paradigm is used given it's
very elaborate and more ergonomic set of tools.

### `tidybayes`, `ggdist`, `distributional` and `extraDistr`

The `ggdist` @R-ggdist and `tidybayes` @R-tidybayes packages are the work horses 
of this book.  `tidybayes` relies heavily on the `ggdist` and reexport
very many of it's functions. In addition `ggdist` is useful for both a frequencist
as well as a bayesian approach.

As a result`ggdist` will be the first choice, `tidybayes` will be used when the 
task is better done with it, in particular for its ability to do the data
with `brms`

The `distributional` package @R-distributional is used with `stat_dist_` functions in `ggdist`
to create slab+interval geoms for analytical distributions.

The `extraDistr` package @R-extraDistr has many extra distributions such as BetaBinom, 
NegBetaBinom, HalfCauchy, ZIP, Pareto, etc. which are useful in real-world
applicaitons and usually dispersed amongst many different packages.

### `bayesplot` and `bayestestR`

`bayesplot` @R-bayesplot and  `bayestestR` @R-bayestestR are used as complement
when `ggdist` and `tidybayes` do not provide a satisfactory solution.


### Using `ggplot2`, `scales`  and `paletteer`

The `ggplot2` package @R-ggplot2 has become the standard for ploting in `R`, no question. There
are 2 packages that really help in making plts with `ggplot`: `scales` and
`paletteer`

The `scales` @R-scales has a whole slew of funcitons to manage scales funciton for
visualization.

The `paletteer` @R-paletteer is a very nice package to manage color and 
shape palettes.


knitr::write_bib(c("loo"), width = 80)

